name: goreleaser

on:
  workflow_call:
    inputs:
      go_version:
        required: false
        type: string
        default: stable
      upload_artifact:
        required: false
        type: boolean
        default: true
    secrets: {}

jobs:
  release:
    runs-on: ubuntu-latest
    # permissions:
    #   contents: write
    #   id-token: write
    #   packages: write
    env:
      DOCKER_CLI_EXPERIMENTAL: enabled
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: actions/setup-go@v5
        with:
          go-version: ${{ inputs.go_version }}
          cache: true
          check-latest: true
      - uses: anchore/sbom-action/download-syft@v0.17.8
      - uses: goreleaser/goreleaser-action@v6
        with:
          version: latest
          args: release --clean
        # env:
        #   GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        #   HOMEBREW_TAP_GITHUB_TOKEN: ${{ secrets.gh_pat }}
        #   GORELEASER_KEY: ${{ secrets.goreleaser_key }}
        #   AUR_KEY: ${{ secrets.aur_key }}
        #   FURY_TOKEN: ${{ secrets.fury_token }}
        #   GPG_KEY_PATH: ${{ runner.temp }}/gpg.key
        #   NFPM_DEFAULT_PASSPHRASE: ${{ secrets.nfpm_passphrase }}
        #   TWITTER_CONSUMER_KEY: ${{ secrets.twitter_consumer_key }}
        #   TWITTER_CONSUMER_SECRET: ${{ secrets.twitter_consumer_secret }}
        #   TWITTER_ACCESS_TOKEN: ${{ secrets.twitter_access_token }}
        #   TWITTER_ACCESS_TOKEN_SECRET: ${{ secrets.twitter_access_token_secret }}
        #   MASTODON_CLIENT_ID: ${{ secrets.mastodon_client_id }}
        #   MASTODON_CLIENT_SECRET: ${{ secrets.mastodon_client_secret }}
        #   MASTODON_ACCESS_TOKEN: ${{ secrets.mastodon_access_token }}
        #   DISCORD_WEBHOOK_ID: ${{ secrets.discord_webhook_id }}
        #   DISCORD_WEBHOOK_TOKEN: ${{ secrets.discord_webhook_token }}
        #   MACOS_SIGN_P12: ${{ secrets.macos_sign_p12 }}
        #   MACOS_SIGN_PASSWORD: ${{ secrets.macos_sign_password }}
        #   MACOS_NOTARY_ISSUER_ID: ${{ secrets.macos_notary_issuer_id }}
        #   MACOS_NOTARY_KEY_ID: ${{ secrets.macos_notary_key_id }}
        #   MACOS_NOTARY_KEY: ${{ secrets.macos_notary_key }}
        #   SNAPCRAFT_STORE_CREDENTIALS: ${{ secrets.snapcraft_token }}

      - uses: actions/upload-artifact@v4
        if: ${{ inputs.upload_artifact == true && always() }}
        with:
          retention-days: 30
          name: dist
          path: |
            dist

# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json