name: goreleaser

on:
  push:
    tags:
      - v*.*.*
  workflow_call:
    inputs:
      go_version:
        required: false
        type: string
        default: stable
      upload_artifact:
        required: false
        type: boolean
        default: true

concurrency:
  group: goreleaser
  cancel-in-progress: true

jobs:
  goreleaser:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    #   id-token: write
    #   packages: write
    env:
      DOCKER_CLI_EXPERIMENTAL: enabled
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: actions/setup-go@v5
        with:
          go-version: ${{ inputs.go_version }}
          cache: true
          check-latest: true
      - uses: anchore/sbom-action/download-syft@v0.17.8
      - uses: goreleaser/goreleaser-action@v6
        with:
          distribution: goreleaser
          version: latest
          args: release --clean
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - uses: actions/upload-artifact@v4
        if: ${{ inputs.upload_artifact == true && always() }}
        with:
          retention-days: 30
          name: dist
          path: |
            dist

# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json